### ISSUE TITLE
raphnet wii guitar not detecting up strum

### ISSUE THREAD

**Issue by thardwardy** [raphaelgoulart/ya_inputdisplay#2]
everything else works fine

**Comment by raphaelgoulart** [comment]
Thanks for the report 🙏 sorry for the obvious question, but did you try clicking on top of the "button" to remap it? (I assume so, asking just in case).

Also, I might do a rewrite on the future to use the win32api for input (so it works with any device regardless of Godot limitations), and check input on a separate thread (so it's FPS independent, and I can lock the FPS to the monitor's refresh rate, saving resources). This _should_ fix that hopefully, but won't be coming anytime soon due to being busy IRL

**Comment by thardwardy** [comment]
yup, I was able to map other buttons to it

**Comment by raphaelgoulart** [comment]
Okay, can you test this app and see how the up strum is detected there (if at all)? https://drive.google.com/file/d/1Y24TnrmKv_N2NbDCRiiirn4XgZ80Kd4V/view?usp=drive_link

This is Godot's official Joypads demo, what's shown there is how Godot reads your controller input.

If the upstrum is seen as an axis, that would be why it doesn't work, as my viewer only detects buttons and d-pad right now. That means i'll have to implement not only reading axes but also calibration (so whammy/tilt aren't wrongly detected as pressed when they're not). Annoying but feasible

If the upstrum is just not detected at all, use [mariko's](https://github.com/marikogh/CHInputViewr) in the meantime, because you'll have to wait for the win32api rewrite (fun!!!!!!!!!!)

**Comment by thardwardy** [comment]
ah yup, it's axis 4. take your time, no rush

**Comment by raphaelgoulart** [comment]
Fixed in https://github.com/raphaelgoulart/ya_inputdisplay/commit/cab92d0aaef58a084df6ee91d03c1ff73c65f213
