### ISSUE TITLE
[Question] Why is there a hidden "FPS" object in the Main.tscn scene?

### ISSUE THREAD

**Issue by SkyJumper409x** [raphaelgoulart/ya_inputdisplay#20]
There seems to be FPS.gd too. Is this something that should be added, is supposed to be added, was removed because of issues...?

**Comment by raphaelgoulart** [comment]
Ah, that's there for when I was testing stuff related to performance, FPS limits, etc early on

The idea is, if you need to test anything related to FPS, just enable that object. Otherwise keep it hidden. But it's not meant for the end user

Let me know if you have further questions! If this answers it fully, please close this issue.

**Comment by SkyJumper409x** [comment]
okay, gotcha
