### ISSUE TITLE
RCM/Santroller Fortnite Festival mode *almost* works with this tool

### ISSUE THREAD

**Issue by LocalH** [raphaelgoulart/ya_inputdisplay#24]
There seem to be only two issues stopping this from being perfectly usable with Fortnite Festival, so I decided to roll them into one.

1) The default Fortnite keyboard binds for pro mode are as follows:

GRYBO: 12345
strum up: right Shift
strum down: Enter
select/tilt: PgDn
start: Esc
whammy: right Ctrl

The relevant ones all seem to map correctly (although I've noticed after clicking on the hamburger menu once and closing it, downstrumming presses Enter and reopens the hamburger menu, which I should be able to avoid by clicking elsewhere in the window). However, the mapping of start to Esc means that the hamburger menu would appear every time the player might press Start on their guitar. This is not really an issue right now, but will be after resolving the second issue.

2) The window only accepts keyboard input (as RCM/Santroller FNF mode uses) when the window is active, making it impossible to use with Fortnite Festival, which only runs at 60fps and only plays the streamed audio when your game window is active. Is there any way to make this tool accept keyboard input anytime, whether or not the window is active?

**Comment by raphaelgoulart** [comment]
2. is not possible due to a Godot limitation, any form of keyboard support is more for testing purposes than anything else

However, I'm testing something out right now, and you _can_ use this tool with Fortnite Festival. In my Santroller, I have a "Fortnite Nestival (Pro Mode - PC gamepad)" Mode Binding, which emulates a FNF-compatible XB1 guitar, and that works perfectly with both the game and my tool

I'll be closing this issue, since 2. not being possible is a dealbreaker for 1. in the first place, and since there's an alternative solution anyway. Appreciate the suggestion, though
